using EmployeeManagementSystem.DataAccess.DBConnection;
using EmployeeManagementSystem.Domain.Constants;
using EmployeeManagementSystem.Domain.Models;

namespace EmployeeManagementSystem.BusinessLogic.OrgFunctions;

public class CostCenterFunctions(IDbUtils dbUtils)
{
    // On success, Data is the new cost center's ID — generated by the DB (NEWSEQUENTIALID()),
    // never by the client, which has no way to supply one (CreateCostCenterRequest has no CostCenterId).
    public async Task<ResponseModel<Guid?>> CreateCostCenterFunction(CreateCostCenterRequest request,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(request.Code))
            return new ResponseModel<Guid?>(400, "Cost center code is required.");
        if (request.Code.Length > FieldLengthConstants.CostCenterCode)
            return new ResponseModel<Guid?>(400, "Cost center code is too long.");
        if (request.Name?.Length > FieldLengthConstants.CostCenterName)
            return new ResponseModel<Guid?>(400, "Cost center name is too long.");

        return await dbUtils.CreateCostCenter(request, cancellationToken);
    }

    public async Task<ResponseModel<CostCenterModel>> GetCostCenterFunction(Guid costCenterId,
        CancellationToken cancellationToken = default)
    {
        if (costCenterId == Guid.Empty)
            return new ResponseModel<CostCenterModel>(400, "A valid cost center ID is required.");

        return await dbUtils.GetCostCenter(costCenterId, cancellationToken);
    }

    public async Task<ResponseModel<IReadOnlyList<CostCenterModel>>> GetCostCentersFunction(
        CancellationToken cancellationToken = default) =>
        await dbUtils.GetCostCenters(cancellationToken);

    public async Task<ResponseModel<object>> UpdateCostCenterFunction(UpdateCostCenterRequest request,
        CancellationToken cancellationToken = default)
    {
        if (request.CostCenterId == Guid.Empty)
            return new ResponseModel<object>(400, "A valid cost center ID is required.");
        if (request.Code?.Length > FieldLengthConstants.CostCenterCode)
            return new ResponseModel<object>(400, "Cost center code is too long.");
        if (request.Name?.Length > FieldLengthConstants.CostCenterName)
            return new ResponseModel<object>(400, "Cost center name is too long.");

        return await dbUtils.UpdateCostCenter(request, cancellationToken);
    }

    public async Task<ResponseModel<object>> DeleteCostCenterFunction(Guid costCenterId,
        CancellationToken cancellationToken = default)
    {
        if (costCenterId == Guid.Empty)
            return new ResponseModel<object>(400, "A valid cost center ID is required.");

        return await dbUtils.DeleteCostCenter(costCenterId, cancellationToken);
    }

    public async Task<ResponseModel<IReadOnlyList<EmployeeSummaryModel>>> GetEmployeesByCostCenterFunction(Guid costCenterId,
        CancellationToken cancellationToken = default)
    {
        if (costCenterId == Guid.Empty)
            return new ResponseModel<IReadOnlyList<EmployeeSummaryModel>>(400, "A valid cost center ID is required.");

        return await dbUtils.GetEmployeesByCostCenter(costCenterId, cancellationToken);
    }
}
