using EmployeeManagementSystem.DataAccess.DBConnection;
using EmployeeManagementSystem.Domain.Constants;
using EmployeeManagementSystem.Domain.Models;

namespace EmployeeManagementSystem.BusinessLogic.OrgFunctions;

public class CostCenterFunctions(IDbUtils dbUtils)
{
    // On success, Data is the new cost center's ID — generated by the DB (NEWSEQUENTIALID()),
    // never by the client, which has no way to supply one (CreateCostCenterRequest has no CostCenterId).
    public async Task<ResponseModel<Guid?>> CreateCostCenterAsync(CreateCostCenterRequest request,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(request.Code))
            return new ResponseModel<Guid?>(400, "Cost center code is required.");
        if (request.Code.Length > FieldLengthConstants.CostCenterCode)
            return new ResponseModel<Guid?>(400, "Cost center code is too long.");
        if (request.Name?.Length > FieldLengthConstants.CostCenterName)
            return new ResponseModel<Guid?>(400, "Cost center name is too long.");

        return await dbUtils.CreateCostCenterAsync(request, cancellationToken);
    }

    public async Task<ResponseModel<CostCenterModel>> GetCostCenterAsync(Guid costCenterId,
        CancellationToken cancellationToken = default)
    {
        if (costCenterId == Guid.Empty)
            return new ResponseModel<CostCenterModel>(400, "A valid cost center ID is required.");

        return await dbUtils.GetCostCenterAsync(costCenterId, cancellationToken);
    }

    public async Task<ResponseModel<IReadOnlyList<CostCenterModel>>> GetCostCentersAsync(
        CancellationToken cancellationToken = default) =>
        await dbUtils.GetCostCentersAsync(cancellationToken);

    public async Task<ResponseModel<object>> UpdateCostCenterAsync(UpdateCostCenterRequest request,
        CancellationToken cancellationToken = default)
    {
        if (request.CostCenterId == Guid.Empty)
            return new ResponseModel<object>(400, "A valid cost center ID is required.");
        if (request.Code?.Length > FieldLengthConstants.CostCenterCode)
            return new ResponseModel<object>(400, "Cost center code is too long.");
        if (request.Name?.Length > FieldLengthConstants.CostCenterName)
            return new ResponseModel<object>(400, "Cost center name is too long.");

        return await dbUtils.UpdateCostCenterAsync(request, cancellationToken);
    }

    public async Task<ResponseModel<object>> DeleteCostCenterAsync(Guid costCenterId,
        CancellationToken cancellationToken = default)
    {
        if (costCenterId == Guid.Empty)
            return new ResponseModel<object>(400, "A valid cost center ID is required.");

        return await dbUtils.DeleteCostCenterAsync(costCenterId, cancellationToken);
    }

    public async Task<ResponseModel<IReadOnlyList<EmployeeSummaryModel>>> GetEmployeesByCostCenterAsync(Guid costCenterId,
        CancellationToken cancellationToken = default)
    {
        if (costCenterId == Guid.Empty)
            return new ResponseModel<IReadOnlyList<EmployeeSummaryModel>>(400, "A valid cost center ID is required.");

        return await dbUtils.GetEmployeesByCostCenterAsync(costCenterId, cancellationToken);
    }
}
