using EmployeeManagementSystem.DataAccess.DBConnection;
using EmployeeManagementSystem.Domain.Constants;
using EmployeeManagementSystem.Domain.Models;

namespace EmployeeManagementSystem.BusinessLogic.OrgFunctions;

public class DepartmentFunctions(IDbUtils dbUtils)
{
    // On success, Data is the new department's ID — generated by the DB (NEWSEQUENTIALID()),
    // never by the client, which has no way to supply one (CreateDepartmentRequest has no DepartmentId).
    public async Task<ResponseModel<Guid?>> CreateDepartmentAsync(CreateDepartmentRequest request,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(request.Name))
            return new ResponseModel<Guid?>(400, "Department name is required.");
        if (request.Name.Length > FieldLengthConstants.DepartmentName)
            return new ResponseModel<Guid?>(400, "Department name is too long.");

        return await dbUtils.CreateDepartmentAsync(request, cancellationToken);
    }

    public async Task<ResponseModel<DepartmentModel>> GetDepartmentAsync(Guid departmentId,
        CancellationToken cancellationToken = default)
    {
        if (departmentId == Guid.Empty)
            return new ResponseModel<DepartmentModel>(400, "A valid department ID is required.");

        return await dbUtils.GetDepartmentAsync(departmentId, cancellationToken);
    }

    public async Task<ResponseModel<IReadOnlyList<DepartmentModel>>> GetDepartmentsAsync(
        CancellationToken cancellationToken = default) =>
        await dbUtils.GetDepartmentsAsync(cancellationToken);

    public async Task<ResponseModel<object>> UpdateDepartmentAsync(UpdateDepartmentRequest request,
        CancellationToken cancellationToken = default)
    {
        if (request.DepartmentId == Guid.Empty)
            return new ResponseModel<object>(400, "A valid department ID is required.");
        if (request.Name?.Length > FieldLengthConstants.DepartmentName)
            return new ResponseModel<object>(400, "Department name is too long.");

        return await dbUtils.UpdateDepartmentAsync(request, cancellationToken);
    }

    public async Task<ResponseModel<object>> DeleteDepartmentAsync(Guid departmentId,
        CancellationToken cancellationToken = default)
    {
        if (departmentId == Guid.Empty)
            return new ResponseModel<object>(400, "A valid department ID is required.");

        return await dbUtils.DeleteDepartmentAsync(departmentId, cancellationToken);
    }

    public async Task<ResponseModel<IReadOnlyList<EmployeeSummaryModel>>> GetEmployeesByDepartmentAsync(Guid departmentId,
        CancellationToken cancellationToken = default)
    {
        if (departmentId == Guid.Empty)
            return new ResponseModel<IReadOnlyList<EmployeeSummaryModel>>(400, "A valid department ID is required.");

        return await dbUtils.GetEmployeesByDepartmentAsync(departmentId, cancellationToken);
    }
}
