using EmployeeManagementSystem.DataAccess.DBConnection;
using EmployeeManagementSystem.Domain.Constants;
using EmployeeManagementSystem.Domain.Models;

namespace EmployeeManagementSystem.BusinessLogic.OrgFunctions;

public class OfficeFunctions(IDbUtils dbUtils)
{
    // On success, Data is the new office's ID — generated by the DB (NEWSEQUENTIALID()),
    // never by the client, which has no way to supply one (CreateOfficeRequest has no OfficeId).
    public async Task<ResponseModel<Guid?>> CreateOfficeFunction(CreateOfficeRequest request,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(request.Name))
            return new ResponseModel<Guid?>(400, "Office name is required.");
        if (request.Name.Length > FieldLengthConstants.OfficeName)
            return new ResponseModel<Guid?>(400, "Office name is too long.");
        if (request.City?.Length > FieldLengthConstants.City)
            return new ResponseModel<Guid?>(400, "City is too long.");
        if (request.Country?.Length > FieldLengthConstants.Country)
            return new ResponseModel<Guid?>(400, "Country is too long.");

        return await dbUtils.CreateOffice(request, cancellationToken);
    }

    public async Task<ResponseModel<OfficeModel>> GetOfficeFunction(Guid officeId,
        CancellationToken cancellationToken = default)
    {
        if (officeId == Guid.Empty)
            return new ResponseModel<OfficeModel>(400, "A valid office ID is required.");

        return await dbUtils.GetOffice(officeId, cancellationToken);
    }

    public async Task<ResponseModel<IReadOnlyList<OfficeModel>>> GetOfficesFunction(
        CancellationToken cancellationToken = default) =>
        await dbUtils.GetOffices(cancellationToken);

    public async Task<ResponseModel<object>> UpdateOfficeFunction(UpdateOfficeRequest request,
        CancellationToken cancellationToken = default)
    {
        if (request.OfficeId == Guid.Empty)
            return new ResponseModel<object>(400, "A valid office ID is required.");
        if (request.Name?.Length > FieldLengthConstants.OfficeName)
            return new ResponseModel<object>(400, "Office name is too long.");
        if (request.City?.Length > FieldLengthConstants.City)
            return new ResponseModel<object>(400, "City is too long.");
        if (request.Country?.Length > FieldLengthConstants.Country)
            return new ResponseModel<object>(400, "Country is too long.");

        return await dbUtils.UpdateOffice(request, cancellationToken);
    }

    public async Task<ResponseModel<object>> DeleteOfficeFunction(Guid officeId,
        CancellationToken cancellationToken = default)
    {
        if (officeId == Guid.Empty)
            return new ResponseModel<object>(400, "A valid office ID is required.");

        return await dbUtils.DeleteOffice(officeId, cancellationToken);
    }

    public async Task<ResponseModel<IReadOnlyList<EmployeeSummaryModel>>> GetEmployeesByOfficeFunction(Guid officeId,
        CancellationToken cancellationToken = default)
    {
        if (officeId == Guid.Empty)
            return new ResponseModel<IReadOnlyList<EmployeeSummaryModel>>(400, "A valid office ID is required.");

        return await dbUtils.GetEmployeesByOffice(officeId, cancellationToken);
    }
}
