namespace EmployeeManagementSystem.Domain.Models;

// Response shape: an employee as read back from the DB. Nullability mirrors the columns:
// BirthDate and the job-info fields are the only NULLable ones.
public sealed record EmployeeModel
{
    public required Guid EmployeeId { get; init; }

    public required string FirstName { get; init; }

    public required string LastName { get; init; }

    public required string PhoneNumber { get; init; }

    public required string Email { get; init; }

    public required EmployeeStatus Status { get; init; }

    // UTC.
    public required DateTime CreatedAt { get; init; }

    // UTC.
    public required DateTime LastInteractionAt { get; init; }

    public required Gender Gender { get; init; }

    public DateOnly? BirthDate { get; init; }

    public required AddressModel Address { get; init; }

    public DateOnly? HireDate { get; init; }

    public Guid? OfficeId { get; init; }

    public string? OfficeName { get; init; }

    public Guid? DepartmentId { get; init; }

    public string? DepartmentName { get; init; }

    public Guid? CostCenterId { get; init; }

    public string? CostCenterName { get; init; }

    // Read-only: the most recent EmployeeSalary entry for this employee
    // (see Employee_Get/Employee_List). Never set on create/edit — salary is
    // append-only history, changed only via EmployeeController's salary-history endpoint.
    public decimal? CurrentGrossSalary { get; init; }
}

// Request shape for POST register. Deliberately all-nullable with no [Required], same
// reasoning as EmployerCredentials: EmployeeRegistration validates every field itself, so a
// missing one gets this app's uniform 400 ResponseModel with a field-specific message.
// There's no EmployeeId: a new employee's key is always generated by the DB.
public sealed class CreateEmployeeRequest
{
    public string? FirstName { get; set; }

    public string? LastName { get; set; }

    public string? PhoneNumber { get; set; }

    public string? Email { get; set; }

    // Omitted = Gender.NotDeclared.
    public Gender? Gender { get; set; }

    public DateOnly? BirthDate { get; set; }

    // Omitted = Active. The only other value accepted is Test (the About page's bulk
    // generator) — see EmployeeRegistration.
    public EmployeeStatus? Status { get; set; }

    public AddressRequest? Address { get; set; }

    public DateOnly? HireDate { get; set; }

    public Guid? OfficeId { get; set; }

    public Guid? DepartmentId { get; set; }

    public Guid? CostCenterId { get; set; }
}

// Request shape for PATCH edit: a partial update, so every field but EmployeeId is optional
// and an omitted one is left unchanged (Employee_Update's ISNULL(@param, column)). There's no
// Status: edit is not a lifecycle transition (that's deactivate/reactivate/delete), so a
// status can't even be expressed here.
public sealed class UpdateEmployeeRequest
{
    public Guid EmployeeId { get; set; }

    public string? FirstName { get; set; }

    public string? LastName { get; set; }

    public string? PhoneNumber { get; set; }

    public string? Email { get; set; }

    public Gender? Gender { get; set; }

    public DateOnly? BirthDate { get; set; }

    public AddressRequest? Address { get; set; }

    public DateOnly? HireDate { get; set; }

    public Guid? OfficeId { get; set; }

    public Guid? DepartmentId { get; set; }

    public Guid? CostCenterId { get; set; }
}

// The one key Employee_Get looks an employee up by — EmployeeGetting fills exactly one
// member, chosen from the search term's shape.
public sealed record EmployeeLookup(Guid? EmployeeId = null, string? PhoneNumber = null, string? Email = null);

// A minimal projection of an employee for "which employees belong to this
// office/department/cost center" listings — deliberately not the full
// EmployeeModel (no address/hire-date/salary), which those queries don't join.
public sealed record EmployeeSummaryModel
{
    public required Guid EmployeeId { get; init; }

    public required string FirstName { get; init; }

    public required string LastName { get; init; }

    public required string Email { get; init; }

    public required EmployeeStatus Status { get; init; }
}
