<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <UserSecretsId>8c896ca6-68ce-4a92-b8ab-cd231667c435</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\EmployeeManagementSystem.BusinessLogic\EmployeeManagementSystem.BusinessLogic.csproj" />
    </ItemGroup>

</Project>
