using EmployeeManagementSystem.BusinessLogic.Validations;
using EmployeeManagementSystem.DataAccess.DBConnection;
using EmployeeManagementSystem.Domain.Constants;
using EmployeeManagementSystem.Domain.Models;

namespace EmployeeManagementSystem.BusinessLogic.EmployeeFunctions;

public class EmployeeRegistration(IDbUtils dbUtils, IEmployeeAuditLogger auditLogger)
{
    // On success, Data is the new employee's GUID — generated by the DB (NEWSEQUENTIALID()),
    // never by the client, which has no way to supply one (CreateEmployeeRequest has no EmployeeId).
    public async Task<ResponseModel<Guid?>> RegisterEmployeeFunction(CreateEmployeeRequest request, string performedBy,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(request.FirstName))
            return new ResponseModel<Guid?>(400, "First name is required.");
        if (request.FirstName.Length > FieldLengthConstants.FirstName)
            return new ResponseModel<Guid?>(400, "First name is too long.");

        if (string.IsNullOrWhiteSpace(request.LastName))
            return new ResponseModel<Guid?>(400, "Last name is required.");
        if (request.LastName.Length > FieldLengthConstants.LastName)
            return new ResponseModel<Guid?>(400, "Last name is too long.");

        if (string.IsNullOrEmpty(request.Email) || EmailValidation.ValidateEmail(request.Email) == false)
            return new ResponseModel<Guid?>(400, "Invalid or empty Email.");
        if (request.Email.Length > FieldLengthConstants.Email)
            return new ResponseModel<Guid?>(400, "Email is too long.");

        if (string.IsNullOrEmpty(request.PhoneNumber) || PhoneNumberValidation.ValidatePhoneNumber(request.PhoneNumber) == false)
            return new ResponseModel<Guid?>(400, "Invalid or empty phone number.");

        // No BirthDate check: its format is guaranteed by the type (DateOnly) — a malformed
        // value is already rejected while the request body is deserialized.

        if (request.Gender is { } gender && !Enum.IsDefined(gender))
            return new ResponseModel<Guid?>(400, "Invalid Gender value.");

        if (request.Address is null)
            return new ResponseModel<Guid?>(400, "Address is required.");

        var addressError = AddressValidation.ValidateRequired(request.Address)
                           ?? AddressValidation.ValidateLengths(request.Address);
        if (addressError is not null)
            return new ResponseModel<Guid?>(400, addressError);

        // A new employee is active by default. The only other status a caller may request at
        // creation time is Test (used by the About page's bulk test-data generator) — anything
        // else (e.g. Deactivated) would bypass the deactivate/reactivate/delete lifecycle rules
        // that are otherwise enforced by the stored procedures.
        if (request.Status is not null and not (EmployeeStatus.Active or EmployeeStatus.Test))
            return new ResponseModel<Guid?>(400, "Invalid employee status.");

        var response = await dbUtils.RegisterEmployee(request, cancellationToken);

        // Deliberately not forwarding cancellationToken here: the employee was already created
        // successfully, so the audit write should still be attempted even if the client that
        // triggered it has since disconnected — same best-effort guarantee EmployeeAuditLogger
        // already gives on write failures, just not conditional on the caller still being there.
        if (response is { Status: 200, Data: { } employeeId })
            await auditLogger.Log(employeeId, performedBy, AuditAction.Created,
                $"Email: {request.Email}, Phone number: {request.PhoneNumber}");

        return response;
    }
}
